version: "2.1"

services:
  landings:
    container_name: landings
    image: landings
    restart: always
    build: .
    environment:
      NODE_ENV: dev
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: 50m
