version: "2.1"

services:
  landings:
    container_name: infra-test
    image: infra-test
    restart: always
    build: .
    environment:
      NODE_ENV: production
    ports:
      - "3000:3000"
    logging:
      options:
        max-size: 50m
