# Use the latest 2.1 version of CircleCI pipeline process engine.
# See: https://circleci.com/docs/2.0/configuration-reference
version: 2.1

# Define a job to be invoked later in a workflow.
# See: https://circleci.com/docs/2.0/configuration-reference/#jobs
jobs:
  deploy-prod:
    docker:
      - image: cimg/node:14.18.0
    working_directory: ~/ronaenserie
    steps:
      - add_ssh_keys:
          fingerprints:
            - "93:93:f3:33:3b:27:37:9f:02:10:df:53:40:1e:84:8f"
      - checkout
      - run:
          name: Add IP to known_hosts
          command: ssh-keyscan $DEPLOY_HOST >> ~/.ssh/known_hosts
      - deploy:
          command: ssh -o "StrictHostKeyChecking no" ubuntu@$DEPLOY_HOST -y "cd ~/ronaenserie;git stash;git checkout main; git pull origin main; sudo docker-compose -f docker-compose-prod.yml up --build -d; sudo docker system prune -f";

workflows:
  build-deploy:
    jobs:
      - deploy-prod:
          filters:
            branches:
              only: main
